package com.shahinst.cdnscanner.scan

/** Edge data-center (IATA) code -> "City, CC". Same table as app/scanner/colo.py. */
object Colo {
    private val NAMES: Map<String, String> = mapOf(
        "ABJ" to "Abidjan, CI",
        "ABQ" to "Albuquerque, US",
        "ACC" to "Accra, GH",
        "ADD" to "Addis Ababa, ET",
        "ADL" to "Adelaide, AU",
        "AKL" to "Auckland, NZ",
        "ALA" to "Almaty, KZ",
        "ALG" to "Algiers, DZ",
        "AMD" to "Ahmedabad, IN",
        "AMM" to "Amman, JO",
        "AMS" to "Amsterdam, NL",
        "ARN" to "Stockholm, SE",
        "ASU" to "Asuncion, PY",
        "ATH" to "Athens, GR",
        "ATL" to "Atlanta, US",
        "AUS" to "Austin, US",
        "BAH" to "Manama, BH",
        "BCN" to "Barcelona, ES",
        "BEG" to "Belgrade, RS",
        "BER" to "Berlin, DE",
        "BEY" to "Beirut, LB",
        "BGW" to "Baghdad, IQ",
        "BKK" to "Bangkok, TH",
        "BLR" to "Bangalore, IN",
        "BNA" to "Nashville, US",
        "BNE" to "Brisbane, AU",
        "BOG" to "Bogota, CO",
        "BOM" to "Mumbai, IN",
        "BOS" to "Boston, US",
        "BRU" to "Brussels, BE",
        "BSB" to "Brasilia, BR",
        "BSR" to "Basra, IQ",
        "BTS" to "Bratislava, SK",
        "BUD" to "Budapest, HU",
        "BUF" to "Buffalo, US",
        "BWI" to "Baltimore, US",
        "CAI" to "Cairo, EG",
        "CBR" to "Canberra, AU",
        "CCU" to "Kolkata, IN",
        "CDG" to "Paris, FR",
        "CEB" to "Cebu, PH",
        "CGK" to "Jakarta, ID",
        "CGP" to "Chattogram, BD",
        "CHC" to "Christchurch, NZ",
        "CLE" to "Cleveland, US",
        "CLT" to "Charlotte, US",
        "CMB" to "Colombo, LK",
        "CMH" to "Columbus, US",
        "CMN" to "Casablanca, MA",
        "CNF" to "Belo Horizonte, BR",
        "COK" to "Kochi, IN",
        "CPH" to "Copenhagen, DK",
        "CPT" to "Cape Town, ZA",
        "CUR" to "Willemstad, CW",
        "CWB" to "Curitiba, BR",
        "DAC" to "Dhaka, BD",
        "DAR" to "Dar es Salaam, TZ",
        "DEL" to "New Delhi, IN",
        "DEN" to "Denver, US",
        "DFW" to "Dallas, US",
        "DKR" to "Dakar, SN",
        "DME" to "Moscow, RU",
        "DMM" to "Dammam, SA",
        "DOH" to "Doha, QA",
        "DPS" to "Denpasar, ID",
        "DTW" to "Detroit, US",
        "DUB" to "Dublin, IE",
        "DUR" to "Durban, ZA",
        "DUS" to "Dusseldorf, DE",
        "DXB" to "Dubai, AE",
        "EBL" to "Erbil, IQ",
        "EDI" to "Edinburgh, GB",
        "EVN" to "Yerevan, AM",
        "EWR" to "Newark, US",
        "EZE" to "Buenos Aires, AR",
        "FCO" to "Rome, IT",
        "FOR" to "Fortaleza, BR",
        "FRA" to "Frankfurt, DE",
        "FUK" to "Fukuoka, JP",
        "GDL" to "Guadalajara, MX",
        "GIG" to "Rio de Janeiro, BR",
        "GOT" to "Gothenburg, SE",
        "GRU" to "Sao Paulo, BR",
        "GUA" to "Guatemala City, GT",
        "GUM" to "Hagatna, GU",
        "GVA" to "Geneva, CH",
        "GYD" to "Baku, AZ",
        "HAM" to "Hamburg, DE",
        "HAN" to "Hanoi, VN",
        "HBA" to "Hobart, AU",
        "HEL" to "Helsinki, FI",
        "HKG" to "Hong Kong, HK",
        "HND" to "Tokyo, JP",
        "HNL" to "Honolulu, US",
        "HYD" to "Hyderabad, IN",
        "IAD" to "Ashburn, US",
        "IAH" to "Houston, US",
        "ICN" to "Seoul, KR",
        "IND" to "Indianapolis, US",
        "ISB" to "Islamabad, PK",
        "IST" to "Istanbul, TR",
        "JAX" to "Jacksonville, US",
        "JED" to "Jeddah, SA",
        "JNB" to "Johannesburg, ZA",
        "JSR" to "Jashore, BD",
        "KBP" to "Kyiv, UA",
        "KEF" to "Reykjavik, IS",
        "KGL" to "Kigali, RW",
        "KHH" to "Kaohsiung, TW",
        "KHI" to "Karachi, PK",
        "KIV" to "Chisinau, MD",
        "KIX" to "Osaka, JP",
        "KJA" to "Krasnoyarsk, RU",
        "KTM" to "Kathmandu, NP",
        "KUL" to "Kuala Lumpur, MY",
        "KWI" to "Kuwait City, KW",
        "LAD" to "Luanda, AO",
        "LAS" to "Las Vegas, US",
        "LAX" to "Los Angeles, US",
        "LCA" to "Larnaca, CY",
        "LED" to "St. Petersburg, RU",
        "LHE" to "Lahore, PK",
        "LHR" to "London, GB",
        "LIM" to "Lima, PE",
        "LIS" to "Lisbon, PT",
        "LJU" to "Ljubljana, SI",
        "LOS" to "Lagos, NG",
        "LPB" to "La Paz, BO",
        "LUX" to "Luxembourg, LU",
        "LYS" to "Lyon, FR",
        "MAA" to "Chennai, IN",
        "MAD" to "Madrid, ES",
        "MAN" to "Manchester, GB",
        "MCI" to "Kansas City, US",
        "MCT" to "Muscat, OM",
        "MEL" to "Melbourne, AU",
        "MEM" to "Memphis, US",
        "MEX" to "Mexico City, MX",
        "MFE" to "McAllen, US",
        "MFM" to "Macau, MO",
        "MIA" to "Miami, US",
        "MKE" to "Milwaukee, US",
        "MLA" to "Valletta, MT",
        "MLE" to "Male, MV",
        "MNL" to "Manila, PH",
        "MPM" to "Maputo, MZ",
        "MRS" to "Marseille, FR",
        "MRU" to "Port Louis, MU",
        "MSP" to "Minneapolis, US",
        "MSQ" to "Minsk, BY",
        "MSY" to "New Orleans, US",
        "MTY" to "Monterrey, MX",
        "MUC" to "Munich, DE",
        "MVD" to "Montevideo, UY",
        "MXP" to "Milan, IT",
        "NAG" to "Nagpur, IN",
        "NBO" to "Nairobi, KE",
        "NJF" to "Najaf, IQ",
        "NOU" to "Noumea, NC",
        "NRT" to "Tokyo, JP",
        "OKA" to "Naha, JP",
        "OKC" to "Oklahoma City, US",
        "OMA" to "Omaha, US",
        "ORD" to "Chicago, US",
        "ORF" to "Norfolk, US",
        "ORK" to "Cork, IE",
        "ORN" to "Oran, DZ",
        "OSL" to "Oslo, NO",
        "OTP" to "Bucharest, RO",
        "PAT" to "Patna, IN",
        "PBH" to "Thimphu, BT",
        "PDX" to "Portland, US",
        "PER" to "Perth, AU",
        "PHL" to "Philadelphia, US",
        "PHX" to "Phoenix, US",
        "PIT" to "Pittsburgh, US",
        "PMO" to "Palermo, IT",
        "PNH" to "Phnom Penh, KH",
        "PNQ" to "Pune, IN",
        "POA" to "Porto Alegre, BR",
        "PRG" to "Prague, CZ",
        "PTY" to "Panama City, PA",
        "QRO" to "Queretaro, MX",
        "RDU" to "Raleigh, US",
        "RGN" to "Yangon, MM",
        "RIC" to "Richmond, US",
        "RIX" to "Riga, LV",
        "RUH" to "Riyadh, SA",
        "SAL" to "San Salvador, SV",
        "SAN" to "San Diego, US",
        "SAT" to "San Antonio, US",
        "SCL" to "Santiago, CL",
        "SDQ" to "Santo Domingo, DO",
        "SEA" to "Seattle, US",
        "SFO" to "San Francisco, US",
        "SGN" to "Ho Chi Minh City, VN",
        "SIN" to "Singapore, SG",
        "SJC" to "San Jose, US",
        "SJJ" to "Sarajevo, BA",
        "SJO" to "San Jose, CR",
        "SJU" to "San Juan, PR",
        "SKP" to "Skopje, MK",
        "SLC" to "Salt Lake City, US",
        "SMF" to "Sacramento, US",
        "SOF" to "Sofia, BG",
        "STL" to "St. Louis, US",
        "SVX" to "Yekaterinburg, RU",
        "SYD" to "Sydney, AU",
        "TAS" to "Tashkent, UZ",
        "TBS" to "Tbilisi, GE",
        "THR" to "Tehran, IR",
        "TIA" to "Tirana, AL",
        "TLL" to "Tallinn, EE",
        "TLV" to "Tel Aviv, IL",
        "TNR" to "Antananarivo, MG",
        "TPA" to "Tampa, US",
        "TPE" to "Taipei, TW",
        "TUN" to "Tunis, TN",
        "TXL" to "Berlin, DE",
        "UIO" to "Quito, EC",
        "ULN" to "Ulaanbaatar, MN",
        "VIE" to "Vienna, AT",
        "VKO" to "Moscow, RU",
        "VNO" to "Vilnius, LT",
        "WAW" to "Warsaw, PL",
        "YOW" to "Ottawa, CA",
        "YUL" to "Montreal, CA",
        "YVR" to "Vancouver, CA",
        "YWG" to "Winnipeg, CA",
        "YYC" to "Calgary, CA",
        "YYZ" to "Toronto, CA",
        "ZAG" to "Zagreb, HR",
        "ZRH" to "Zurich, CH",
    )

    fun name(code: String?): String = NAMES[(code ?: "").trim().uppercase()] ?: ""

    /** "FRA (Frankfurt, DE)" or just the code when unknown. */
    fun label(code: String?): String {
        val c = (code ?: "").trim().uppercase()
        if (c.isEmpty()) return ""
        val n = name(c)
        return if (n.isEmpty()) c else "$c ($n)"
    }
}
